# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    Djvue\WpAdminBundle\Command\:
        resource: '../../Command'

    Djvue\WpAdminBundle\Configurator\:
        resource: '../../Configurator'

    Djvue\WpAdminBundle\Service\:
        resource: '../../Service'

    Djvue\WpAdminBundle\Loader\LoaderInterface:
        alias: 'Djvue\WpAdminBundle\Loader\Loader'
        public: true
    Djvue\WpAdminBundle\Loader\Loader:
        arguments:
            - !tagged_iterator wp_admin.configurator
    Djvue\WpAdminBundle\Loader\ConfigurationLoaderInterface:
        alias: 'Djvue\WpAdminBundle\Loader\ConfigurationLoader'
    Djvue\WpAdminBundle\Loader\ConfigurationLoader: ~
    Djvue\WpAdminBundle\Loader\ConfiguratorLoaderInterface:
        alias: 'Djvue\WpAdminBundle\Loader\ConfiguratorLoader'
    Djvue\WpAdminBundle\Loader\ConfiguratorLoader: ~

    Djvue\WpAdminBundle\FieldGroup\FieldGroupConfigurator:
        arguments:
            - !tagged_iterator wp_admin.field_group
            - '%wp_admin.enable_cache%'
            - '%kernel.debug%'
    Djvue\WpAdminBundle\Configurator\HostConfigurator:
        arguments:
            - '%wp_admin.host%'
    Djvue\WpAdminBundle\Configurator\PageTemplatesConfigurator:
        arguments:
            - '%wp_admin.page_templates%'

    Djvue\WpAdminBundle\Service\OptionFields:
        arguments:
            - '%wp_admin.enable_options_cache%'
    Djvue\WpAdminBundle\Service\PostFields:
        arguments:
            - '%wp_admin.enable_post_fields_cache%'
